build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  variables:
    IMAGE_TAG: registry.gitlab.com/letstream/psql-backup
  script:
    - export VERSION=$(cat VERSION)
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG:v$VERSION .
    - docker push $IMAGE_TAG
  only:
    - production
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
